### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by sil-varis** [SKIRT/PTS9#41]
**Description**
How can PTS9 be installed on Windows? 
Getting the source code as described in the PTS installation guide for Unix or MacOS on the website (https://skirt.ugent.be/root/_install_p_t_s.html) works out.
 However configuring the paths and aliases does not seem to work the same way on Windows.
 **System**
Windows 11

**Comment by petercamps** [comment]
Thank you for your question. Unfortunately, I don't know anyone who has installed PTS on Windows, and I'm not a Windows expert myself. Is there someone in your environment who might help you with this? If you do figure it out, please let me know and I'll add it to the documentation. If not, please provide me with the specifics of your system (Windows version, python install, ...) and the problems you encounter. I will then have a look -- but no guarantees.

**Comment by sil-varis** [comment]
Thank you for your quick reply! I have done some fidgeting and I used these steps to get it working for me:
1.  Follow the first step of the guide for Linux and MacOS, namely in a terminal go to a chosen directory and execute the following:
 ```
    mkdir PTS
    cd PTS
    mkdir run
    mkdir pts
```
2.  In Git Bash terminal, navigate to PTS directory and execute:
```
git clone https://github.com/SKIRT/PTS9.git pts
```
3. Configure the Python path by opening Settings and searching for environment variables, then clicking "edit system environment variables". A pop-up window opens, which has a button "Environment variables" at the bottom. After clicking this button, a new pop-up window appears, where after clicking "New..." a new environment variable can be created with name `PYTHONPATH` and value `~/PTS` (where ~ is the actual path of the directory).

4.  Create an alias by executing:
```
doskey pts=python -m pts.do $*
```
However the alias is not remembered after closing the terminal window and I have not managed to figure out how to solve this (yet). At the moment, I just execute this line each time I want to use pts.

**Comment by petercamps** [comment]
Many thanks for sharing this information. Next time I update the web site, I'll add it to the installation guide.

**Comment by camlawlorforsyth** [comment]
Hi Peter,

I have a solution for remembering the alias if a Windows user is using Anaconda/Miniconda. After following the above steps to download the PTS source code, and setting the `PYTHONPATH` environment variable, one can find the location of the `anaconda3/Scripts/activate.bat` file (usually located somewhere like `C:/Users/user/anaconda3/Scripts/activate.bat` on Windows 10) and add the doskey after the initial setting of arguments (which ends on line 16):
```
@REM user added aliases
doskey pts=python -m pts.do $*
cls
```
which I adapted from this post: https://stackoverflow.com/questions/68541834

I hope this helps someone in the future! I use Miniconda as my regular python installation on Windows 10, so this isn't comprehensive for all use cases, but my understanding is that Anaconda/Miniconda is fairly widely used on Windows.

Let me know if there's anything else I can help clarify for this solution,
Cam

**Comment by petercamps** [comment]
@camlawlorforsyth Thanks! Next time I update the web site, I'll add it to the installation guide.
